# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 919b55f2f0afe70bd532f50182a2f98ec7b769f153a385aacf1a084e58ad6cf4a1c130764a66a744fa06dc44c365596574709768e39fbf7fbb0ab4fb4fc9764c

test:
  secret_key_base: 78d49ec092a83c115c3c6920f142c081145ce9899b272fdf1d758c5f9662ca5aaeb94302e3f96610354ef2b88b558bca686c5bc3b8a52fa56bb4e77e30a15396

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
